# Generated by Django 5.0.2 on 2024-02-21 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_laptop_students_laptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='created',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='students',
            name='laptop',
        ),
        migrations.AddField(
            model_name='laptop',
            name='serial_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.students'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laptop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.students')),
            ],
        ),
    ]
