# Generated by Django 5.0.2 on 2024-02-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_laptop_created_remove_laptop_serial_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='laptop',
        ),
    ]
