# Generated by Django 5.0.2 on 2024-03-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_students_brand_students_serial_number_delete_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='img',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
