# Generated by Django 5.0.2 on 2024-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('card_id', models.CharField(max_length=100, unique=True)),
                ('card_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('teacher', 'Teacher'), ('visitor', 'Visitor')], max_length=10)),
                ('face_encoding', models.TextField()),
                ('gender', models.CharField(max_length=255, null=True)),
                ('img', models.TextField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
