# Generated by Django 5.0.6 on 2024-06-26 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person'),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
