# Generated by Django 5.1 on 2024-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_exitrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='serial_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
